dismiss_old_notifications:
  fields:
    keep_days:
      selector:
        number:
          min: 0
          max: 365
          unit_of_measurement: days
    notification_id_filter:
      selector:
        text: