blueprint:
  name: Leak Annoucement
  description: |
    Announce when a leak occurs and shutoff water
  domain: automation
  source_url: https://github.com/alexyao2015/homeassistantYAML/blob/master/blueprints/leak_annoucement.yaml
  input:
    leak_sensor:
      name: Leak Sensor
      description: The leak sensor to watch for leaks.
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
    water_shutoff:
      name: (Optional) Water Shutoff Valve
      description: The water shutoff valve to turn off if a leak has been detected
      default: ""
      selector:
        entity:
          domain: switch
    announcement_count:
      name: Announcement Count
      description: Number of times to announce a leak has occurred
      default: "1"
      selector:
        number:
          min: 1
          max: 1000
          mode: box
    announcement_delay:
      name: Announcement Delay
      description: Delay between each announcement
      default: "00:01:00"
      selector:
        duration:
mode: single
max_exceeded: silent

variables:
  leak_sensor: !input leak_sensor
  water_shutoff: !input water_shutoff
  announcement_count: !input announcement_count
  announcement_delay: !input announcement_delay

  trigger_entity_id: "{{ trigger.entity_id }}"
  trigger_entity_name: "{{ trigger.to_state.attributes.friendly_name }}"

trigger:
  - platform: template
    value_template: "{{ states(leak_sensor) == 'on' }}"

action:
  - choose:
      - conditions: "{{ not not water_shutoff }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ water_shutoff }}"

  - repeat:
      until:
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ repeat.index > announcement_count }}"
            - condition: template
              value_template: '{{ states(trigger_entity_id) == "off" }}'
      sequence:
        - service: script.turn_on
          data:
            variables:
              message: A leak was detected on the "{{ trigger_entity_name }}" sensor
          target:
            entity_id: script.notify_everywhere
          enabled: false
        - delay: "{{ announcement_delay }}"
